### PR TITLE
Fed strokes for factions and clean custom fed

### PR DESCRIPTION
**Pull request by rzulian**
Solves #50 and improves every faction

### CODE REVIEW

**Comment by coyotte508** [comment]
Can I have screenshots? Also when two federations occupy the same spot ? :) (like lantids & another on the same planet)

**Comment by rzulian** [comment]
screen shot 2018-08-02 at 08 12 54

**Comment by rzulian** [comment]
screen shot 2018-08-02 at 15 35 37

**Comment by coyotte508** [comment]
Nice job!!

**Pull request merged**
