### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by coyotte508**
Can't play the current version anymore. Please merge!

image

image

### CODE REVIEW

**Comment by coyotte508** [comment]
Added a prefernece to show flat buildings on the map (just the map):

image

**Comment by rzulian** [comment]
**1. light in the buildings is inconsistent.**
Screenshot 2020-06-25 at 17 43 15


This is also affecting the coloured buildings. The problem is that the color filter applies to grey base building, and the before the majority of the building is not the primary color, which is impacting the ability to distinguish the faction on the map, especially on mobile. In the final building we have a darker color, a color close to the faction color, and a lighter color, difficult to distinguish in small screens

Screenshot 2020-06-25 at 16 35 03

**2. bold lines** 
There are a lot of different bold ones that are confusing instead of helping

Screenshot 2020-06-25 at 17 45 59
Screenshot 2020-06-25 at 17 46 31
Screenshot 2020-06-25 at 17 46 45

Suggestion: move to a thin consistent line for resources, tiles, building. I would start with the one we are using for qics

**Comment by rzulian** [comment]
3. tile. icons alignment
Icons are not aligned and also overlapping the victory point icon. Move them aligned bottom.
Screenshot 2020-06-25 at 18 51 13

**Comment by rzulian** [comment]
4. action tiles position
This is inconsistent with the boardgames, and also wasting precious space for the map.
Move it to the bottom horizontally and maximise the board
Screenshot 2020-06-25 at 18 59 35

**Comment by rzulian** [comment]
5. I cannot relate the red hexagon to the end turn

**Comment by rzulian** [comment]
**6. highlight buildings on map**
Instead of the bold lines only, can we evaluate something like this?

Screenshot 2020-06-25 at 19 15 27
Screenshot 2020-06-25 at 19 15 37

**Pull request merged**
